module.exports = [
  "Voetbal is simpel. Maar simpel voetballen is het moeilijkste wat er is.",
  "Elk nadeel heb z’n voordeel.",
  "Je gaat het pas zien als je het doorhebt.",
  "Je moet schieten, anders kun je niet scoren.",
  "Als wij de bal hebben, kunnen zij niet scoren.",
  "Italië kan je niet verslaan, maar je kunt er wel van winnen.",
  "Ik ben overal tegen. Tot ik een besluit neem, dan ben ik ervoor.",
  "In zekere zin ben ik waarschijnlijk onsterfelijk.",
  "Soms moet er iets gebeuren voordat er iets gebeurt.",
  "Als je niet kunt winnen, moet je zorgen dat je niet verliest.",
  "Je moet altijd zorgen dat je één doelpunt meer scoort dan de tegenstander.",
  "Voetbal is simpel. Maar simpel voetballen is het moeilijkste wat er is.",
  "Als je niet kunt winnen, moet je zorgen dat je niet verliest.",
  "Ik ben overal tegen. Tot ik een besluit neem, dan ben ik ervoor.",
  "Elk nadeel heb z’n voordeel.",
  "Als wij de bal hebben, kunnen zij niet scoren.",
  "Soms moet er iets gebeuren voordat er iets gebeurt.",
  "Zonder de bal kun je niet winnen.",
  "Je gaat het pas zien als je het doorhebt.",
  "Ik hou van werken, zolang het werken is wat ik leuk vind.",
  "Ik ben niet bijgelovig, want dat brengt ongeluk.",
  "Je moet schieten, anders kun je niet scoren.",
  "Waarom zou ik een joggingbroek dragen? Ik heb toch geen tijd om te joggen.",
  "Als je één doelpunt meer maakt dan de ander, dan win je.",
  "Het moeilijkste van een makkelijke kans is hem makkelijk te maken.",
  "Voordat ik een fout maak, maak ik die fout niet.",
  "Italië kan je niet verslaan, maar je kunt er wel van winnen.",
  "Ik geloof niet in toeval. Toeval is logisch.",
  "In zekere zin ben ik waarschijnlijk onsterfelijk.",
  "Wat is snelheid? Dat is vaak verwarring.",
  "Als je vooruit wilt denken, moet je eerst stilstaan.",
  "De bal gaat sneller dan de benen, behalve als je te laat bent.",
  "Als je het simpel houdt, hoef je minder fouten te verbeteren.",
  "Een goede speler weet waar hij niet moet staan.",
  "Je hoeft het niet te begrijpen om het goed te doen, maar het helpt wel.",
  "Pas als je zonder nadenken goed speelt, heb je er goed over nagedacht.",
  "Rust is snelheid in vermomming.",
  "Een team wint niet omdat het beter is, maar omdat het beter samen is.",
  "Iedereen kan de juiste keuze maken, maar niet iedereen maakt ‘m op tijd.",
  "Als je de bal niet hebt, kun je niet verliezen — maar je wint er ook niks mee.",
  "Alleen als je wint heb je vrienden.",
  "Door de bomen de bossen niet meer zien."
  "De bal is rond, maar de wedstrijd is vierkant.",
  "Waarom de bal rond is? Omdat hij anders niet zou rollen.",
];

