module.exports = [
  "Voetbal is simpel. Maar simpel voetballen is het moeilijkste wat er is.",
  "Elk nadeel heb z’n voordeel.",
  "Je gaat het pas zien als je het doorhebt.",
  "Je moet schieten, anders kun je niet scoren.",
  "Als wij de bal hebben, kunnen zij niet scoren.",
  "Italië kan je niet verslaan, maar je kunt er wel van winnen.",
  "Ik ben overal tegen. Tot ik een besluit neem, dan ben ik ervoor.",
  "In zekere zin ben ik waarschijnlijk onsterfelijk.",
  "Soms moet er iets gebeuren voordat er iets gebeurt.",
  "Als je niet kunt winnen, moet je zorgen dat je niet verliest.",
  "Je moet altijd zorgen dat je één doelpunt meer scoort dan de tegenstander.",
  "Voetbal is simpel. Maar simpel voetballen is het moeilijkste wat er is.",
  "Als je niet kunt winnen, moet je zorgen dat je niet verliest.",
  "Ik ben overal tegen. Tot ik een besluit neem, dan ben ik ervoor.",
  "Elk nadeel heb z’n voordeel.",
  "Als wij de bal hebben, kunnen zij niet scoren.",
  "Soms moet er iets gebeuren voordat er iets gebeurt.",
  "Zonder de bal kun je niet winnen.",
  "Je gaat het pas zien als je het doorhebt.",
  "Ik hou van werken, zolang het werken is wat ik leuk vind.",
  "Ik ben niet bijgelovig, want dat brengt ongeluk.",
  "Je moet schieten, anders kun je niet scoren.",
  "Waarom zou ik een joggingbroek dragen? Ik heb toch geen tijd om te joggen.",
  "Als je één doelpunt meer maakt dan de ander, dan win je.",
  "Het moeilijkste van een makkelijke kans is hem makkelijk te maken.",
  "Voordat ik een fout maak, maak ik die fout niet.",
  "Italië kan je niet verslaan, maar je kunt er wel van winnen.",
  "Ik geloof niet in toeval. Toeval is logisch.",
  "In zekere zin ben ik waarschijnlijk onsterfelijk.",
  "Wat is snelheid? Dat is vaak verwarring."
];

